In [1]:
from itertools import groupby

import pandas as pd
import numpy as np

# Goal is to understand
 - transformer

In [18]:
df = pd.DataFrame({
    "customer": ["A", "A", "A", "A", "B", "B", "B", "B"],
    "date": pd.to_datetime([
        "2026-08-01", "2026-08-02", "2026-08-03", "2026-08-04",
        "2026-08-01", "2026-08-02", "2026-08-03", "2026-08-04"
    ]),
    "amount": [100, 200, 300, 400, 50, 150, 250, 350]
})

In [19]:
df

  customer       date  amount
0        A 2026-08-01     100
1        A 2026-08-02     200
2        A 2026-08-03     300
3        A 2026-08-04     400
4        B 2026-08-01      50
5        B 2026-08-02     150
6        B 2026-08-03     250
7        B 2026-08-04     350

## Let's understand aggregation vs Transformer

In [21]:
a_df=df.groupby("customer")["amount"].mean()
a_df

customer
A    250.0
B    200.0
Name: amount, dtype: float64

In [20]:
df['customer_mean']=df.groupby("customer")["amount"].transform('mean')
df

  customer       date  amount  customer_mean
0        A 2026-08-01     100          250.0
1        A 2026-08-02     200          250.0
2        A 2026-08-03     300          250.0
3        A 2026-08-04     400          250.0
4        B 2026-08-01      50          200.0
5        B 2026-08-02     150          200.0
6        B 2026-08-03     250          200.0
7        B 2026-08-04     350          200.0

## Outcome
- groupby aggregation will create report by groupby function
- aggregation will return grouping entire data

### Transform
- It will apply group result to all dataset with same indecis order