## This part I will look for exploring window function in dataframe

In [1]:
import pandas as pd
import numpy as np

In [2]:

df = pd.DataFrame({
    "day": ["Day 1", "Day 2", "Day 3", "Day 4"],
    "sales": [10, 20, 30, 40]
})

print(df)

     day  sales
0  Day 1     10
1  Day 2     20
2  Day 3     30
3  Day 4     40

In [5]:
df["average_last_2"] = (
    df["sales"]
    .rolling(window=2, min_periods=1)
    .mean()
)

print(df)

     day  sales  average_last_2  sum_last_2
0  Day 1     10            10.0        10.0
1  Day 2     20            15.0        30.0
2  Day 3     30            25.0        50.0
3  Day 4     40            35.0        70.0

### What we have learned here
- operation not exactly in same column but
- I can make operation in completely 2 different columns
- After operation I can set result it records

| index | sales | average_last_2 |               math                |               rules                |
|:-----:|:-----:|:--------------:|:---------------------------------:|:----------------------------------:|
|   1   |  10   |       10       | No/ because previous value exists | No because no previous value exist |
|   2   |  20   |       15       |             (10+20)/2             |        index(1)+index(2)/2         |
|   3   |  30   |       25       |             (20+30)/2             |        index(2)+index(3)/2         |
|   4   |  40   |       35       |             (30+40)/2             |        index(3)+index(4)/2         |

In [6]:
df["sum_last_2"] = (
    df["sales"]
    .rolling(window=2, min_periods=1)
    .sum()
)

print(df)

     day  sales  average_last_2  sum_last_2
0  Day 1     10            10.0        10.0
1  Day 2     20            15.0        30.0
2  Day 3     30            25.0        50.0
3  Day 4     40            35.0        70.0


| index | sales | sum_last_2 |               math                |               rules                |
|:-----:|:-----:|:----------:|:---------------------------------:|:----------------------------------:|
|   1   |  10   |     10     | No/ because previous value exists | No because no previous value exist |
|   2   |  20   |     30     |               10+20               |         index(1)+index(2)          |
|   3   |  30   |     50     |               20+30               |         index(2)+index(3)          |
|   4   |  40   |     70     |               30+40               |         index(3)+index(4)          |

In [14]:
df =pd.read_csv('./data/login_reject_history_3000.csv')
df['time_to_attempt']=pd.to_datetime(df['time_to_attempt'])

df.shape

(3000, 9)

In [26]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

df.head(10)

,id,email,device_mac_id,ip,location,time_to_attempt,rejection_reason,is_suspicious,scenario,email_attempt_last_5m
0,3000,user4@example.com,02:E5:8E:03:51:D8,192.0.2.88,"Rajshahi, BD",2026-07-31 23:15:33+00:00,invalid_password,0,normal_user_error,0
1,2999,user8@example.com,02:96:B9:62:23:17,192.0.2.170,"Rajshahi, BD",2026-07-31 22:49:41+00:00,password_typo,0,normal_user_error,0
2,2998,user10@example.com,02:8E:E8:BA:53:BD,192.0.2.91,"Chattogram, BD",2026-07-31 22:47:08+00:00,password_typo,0,normal_user_error,0
3,2997,user2@example.com,02:34:2C:D8:10:0F,192.0.2.24,"Chattogram, BD",2026-07-31 20:17:57+00:00,otp_failed,0,normal_user_error,0
4,2996,user10@example.com,02:A1:4D:E1:22:F0,192.0.2.91,"New York, US",2026-07-31 20:10:34+00:00,invalid_password,0,normal_user_error,0
5,2995,user6@example.com,02:C2:31:B7:B0:87,192.0.2.207,"Chattogram, BD",2026-07-31 20:01:35+00:00,expired_session,0,normal_user_error,0
6,2994,user8@example.com,02:96:B9:62:23:17,192.0.2.170,"Rajshahi, BD",2026-07-31 19:38:34+00:00,invalid_password,0,normal_user_error,0
7,2993,user2@example.com,02:34:2C:D8:10:0F,192.0.2.24,"Chattogram, BD",2026-07-31 18:34:44+00:00,invalid_password,0,normal_user_error,0
8,2992,user2@example.com,02:34:2C:D8:10:0F,192.0.2.24,"Chattogram, BD",2026-07-31 18:17:58+00:00,password_typo,0,normal_user_error,0
9,2991,user5@example.com,02:8E:4F:6E:AC:34,192.0.2.24,"Dhaka, BD",2026-07-31 17:38:17+00:00,invalid_password,0,normal_user_error,0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                3000 non-null   int64
 1   email             3000 non-null   object
 2   device_mac_id     3000 non-null   object
 3   ip                3000 non-null   object
 4   location          3000 non-null   object
 5   time_to_attempt   3000 non-null   datetime64[ns, UTC]
 6   rejection_reason  3000 non-null   object
 7   is_suspicious     3000 non-null   int64
 8   scenario          3000 non-null   object
dtypes: datetime64[ns, UTC](1), int64(2), object(6)
memory usage: 211.1+ KB

In [43]:
df['email_attempt_last_5m']=(
   df.groupby("email", sort=False)
           .rolling(
               window="5min",
               on="time_to_attempt",
               closed="right"
           )["id"]
           .count()
           .astype(int)
           .to_numpy()
)

smallest date time  2026-07-01 00:11:51+00:00
largest date time  2026-07-31 23:15:33+00:00

In [38]:
df.head(10)

,id,email,device_mac_id,ip,location,time_to_attempt,rejection_reason,is_suspicious,scenario,email_attempt_last_5m,_original_row
0,3000,user4@example.com,02:E5:8E:03:51:D8,192.0.2.88,"Rajshahi, BD",2026-07-31 23:15:33+00:00,invalid_password,0,normal_user_error,1,0
1,2999,user8@example.com,02:96:B9:62:23:17,192.0.2.170,"Rajshahi, BD",2026-07-31 22:49:41+00:00,password_typo,0,normal_user_error,1,1
2,2998,user10@example.com,02:8E:E8:BA:53:BD,192.0.2.91,"Chattogram, BD",2026-07-31 22:47:08+00:00,password_typo,0,normal_user_error,1,2
3,2997,user2@example.com,02:34:2C:D8:10:0F,192.0.2.24,"Chattogram, BD",2026-07-31 20:17:57+00:00,otp_failed,0,normal_user_error,1,3
4,2996,user10@example.com,02:A1:4D:E1:22:F0,192.0.2.91,"New York, US",2026-07-31 20:10:34+00:00,invalid_password,0,normal_user_error,1,4
5,2995,user6@example.com,02:C2:31:B7:B0:87,192.0.2.207,"Chattogram, BD",2026-07-31 20:01:35+00:00,expired_session,0,normal_user_error,1,5
6,2994,user8@example.com,02:96:B9:62:23:17,192.0.2.170,"Rajshahi, BD",2026-07-31 19:38:34+00:00,invalid_password,0,normal_user_error,1,6
7,2993,user2@example.com,02:34:2C:D8:10:0F,192.0.2.24,"Chattogram, BD",2026-07-31 18:34:44+00:00,invalid_password,0,normal_user_error,1,7
8,2992,user2@example.com,02:34:2C:D8:10:0F,192.0.2.24,"Chattogram, BD",2026-07-31 18:17:58+00:00,password_typo,0,normal_user_error,1,8
9,2991,user5@example.com,02:8E:4F:6E:AC:34,192.0.2.24,"Dhaka, BD",2026-07-31 17:38:17+00:00,invalid_password,0,normal_user_error,1,9

In [44]:
df=df.sort_values('time_to_attempt', ascending=False).reset_index(drop=True)

In [51]:
user4_df=df[df['email']=='user4@example.com']
user4_df=user4_df.sort_values('time_to_attempt', ascending=False).reset_index(drop=True)
smallest_datetime = user4_df["time_to_attempt"].min()
largest_datetime = user4_df["time_to_attempt"].max()
print("smallest date time ", smallest_datetime)
print("largest date time ", largest_datetime)

# user4_df.to_csv('user4.csv', index=False)

smallest date time  2026-07-01 02:33:34+00:00
largest date time  2026-07-31 23:15:33+00:00

In [59]:
user4_df['attempt_time_minutes']=np.nan
# ser4_df.drop(columns=['_original_row','location','ip','email'], inplace=True)
for i in range(len(user4_df)):
        user4_df.iloc[i]['attempt_time_minutes']=np.number(i)

user4_df.head(10)

TypeError: cannot create 'numpy.number' instances

In [46]:
df["_original_row"] = np.arange(len(df))


# --------------------------------------------------
# 2. Sort by email and timestamp
# --------------------------------------------------

test_df = (
    df.sort_values(
        ["email", "time_to_attempt", "id"],
        kind="stable"
    )
    .copy()
)


# --------------------------------------------------
# 3. Calculate the expected correct value
# --------------------------------------------------

test_df["expected_email_attempt_last_5m"] = (
    test_df.groupby("email", sort=False)
           .rolling(
               window="5min",
               on="time_to_attempt",
               closed="right"
           )["id"]
           .count()
           .astype(int)
           .to_numpy()
)


# --------------------------------------------------
# 4. Return to the original CSV order
# --------------------------------------------------

test_df = (
    test_df.sort_values("_original_row")
           .reset_index(drop=True)
)


# --------------------------------------------------
# 5. Compare existing and expected values
# --------------------------------------------------

test_df["is_correct"] = (
    test_df["email_attempt_last_5m"]
    == test_df["expected_email_attempt_last_5m"]
)


# Show summary
total_rows = len(test_df)
correct_rows = test_df["is_correct"].sum()
incorrect_rows = (~test_df["is_correct"]).sum()

print("Total rows:", total_rows)
print("Correct rows:", correct_rows)
print("Incorrect rows:", incorrect_rows)


# --------------------------------------------------
# 6. Show only incorrect records
# --------------------------------------------------

incorrect_records = test_df.loc[
    ~test_df["is_correct"],
    [
        "id",
        "email",
        "time_to_attempt",
        "email_attempt_last_5m",
        "expected_email_attempt_last_5m"
    ]
]

print("\nIncorrect records:")
print(incorrect_records.head(30))

Total rows: 3000
Correct rows: 1794
Incorrect rows: 1206

Incorrect records:
       id               email           time_to_attempt  \
53   2947  user10@example.com 2026-07-31 01:50:50+00:00
54   2946  user10@example.com 2026-07-31 01:27:21+00:00
57   2943   user4@example.com 2026-07-30 23:58:52+00:00
58   2942  user10@example.com 2026-07-30 22:47:41+00:00
65   2935   user1@example.com 2026-07-30 20:18:18+00:00
68   2932   user3@example.com 2026-07-30 19:55:14+00:00
85   2915   user6@example.com 2026-07-30 12:51:10+00:00
100  2900   user5@example.com 2026-07-30 07:08:39+00:00
102  2898  user10@example.com 2026-07-30 06:52:42+00:00
103  2897  user10@example.com 2026-07-30 06:30:50+00:00
105  2895   user9@example.com 2026-07-30 05:43:13+00:00
106  2894   user7@example.com 2026-07-30 05:14:58+00:00
107  2893   user6@example.com 2026-07-30 04:54:52+00:00
108  2892   user2@example.com 2026-07-30 04:28:05+00:00
109  2891  user10@example.com 2026-07-30 03:50:32+00:00
110  2890   user5@example.com 2026-07-30 03:31:48+00:00
111  2889   user8@example.com 2026-07-30 02:46:25+00:00
112  2888   user4@example.com 2026-07-30 02:33:23+00:00
113  2887   user1@example.com 2026-07-30 01:44:46+00:00
114  2886   user2@example.com 2026-07-30 01:36:31+00:00
115  2885   user1@example.com 2026-07-30 00:57:35+00:00
116  2884   user2@example.com 2026-07-30 00:45:47+00:00
117  2883   user4@example.com 2026-07-29 23:33:38+00:00
118  2882   user5@example.com 2026-07-29 23:33:35+00:00
119  2881   user1@example.com 2026-07-29 23:27:00+00:00
120  2880   user8@example.com 2026-07-29 23:15:04+00:00
121  2879  user10@example.com 2026-07-29 23:09:11+00:00
122  2878   user7@example.com 2026-07-29 22:52:00+00:00
126  2874   user3@example.com 2026-07-29 22:31:54+00:00
127  2873   user8@example.com 2026-07-29 21:22:45+00:00

     email_attempt_last_5m  expected_email_attempt_last_5m
53                       2                               1
54                       3                               1
57                       2                               1
58                       3                               1
65                       2                               1
68                       2                               1
85                       2                               1
100                      2                               1
102                      2                               1
103                      3                               1
105                      2                               1
106                      3                               1
107                      4                               1
108                      5                               1
109                      6                               1
110                      7                               1
111                      8                               1
112                      9                               1
113                     10                               1
114                     11                               1
115                     12                               1
116                     13                               1
117                     14                               1
118                     15                               1
119                     16                               1
120                     17                               1
121                     18                               1
122                     19                               1
126                      2                               1
127                      3                               1